ACS-GERARDIUM-RUSH-SPHALERITE: Circuit Class Reference
Circuit Class Reference
#include <CCircuit.h>
Public Member Functions
Circuit (int num_units)
Constructs a Circuit with a given number of units.
bool Check_Validity (int vector_size, int *circuit_vector, bool if_debug=false)
Checks the validity of the circuit configuration.
void initialize_units (int *circuit_vector, double F_in_valuable, double F_in_waste)
Initializes the units in the circuit.
void update_input (std::vector< CUnit > &units)
Updates the input flow rates for all units in the circuit.
void one_unit (CUnit &cunit)
Calculates the flow rates for a single unit.
void iterate_units (int max_iterations, double tol)
Iterates through the units in the circuit until convergence or maximum iterations are reached.
bool check_convergence (double tol)
Checks if the circuit has converged based on the tolerance.
void get_input_units (std::vector< CUnit > &Units, int unit_num)
Retrieves all input units for a single unit in the circuit.
void get_all_input_units ()
Retrieves all input units for all units in the circuit.
void get_final_output_source (std::array< CUnit, 2 > &outputs, std::vector< CUnit > &Units)
Retrieves all input units for the final output in the circuit.
void update_final_output (std::array< CUnit, 2 > &fin_output, std::vector< CUnit > &cunits)
Updates the final output with the geradium and waste received.
double evaluate_performance ()
Evaluates the performance of the circuit.
Public Attributes
double initial_F_g
double initial_F_w
int first_feed
bool converged
std::vector< CUnit > units
std::vector< double > output
std::array< CUnit, 2 > final_output
Private Member Functions
void mark_units (int unit_num)
Marks the units starting from a given unit number.
Private Attributes
bool validation [3]
Detailed Description
Header for the circuit class
This header defines the circuit class and its associated functions
Definition at line 13 of file CCircuit.h.
Constructor & Destructor Documentation
Circuit()
Circuit::Circuit (int num_units)
Constructs a Circuit with a given number of units.
Parameters
num_units The number of units in the circuit.
Definition at line 9 of file CCircuit.cpp.
{
    this->units.resize(num_units);
}
References units.
Member Function Documentation
check_convergence()
bool Circuit::check_convergence (double tol)
Checks if the circuit has converged based on the tolerance.
Parameters
tol Convergence tolerance.
Returns
true if the circuit has converged.
false if the circuit has not converged.
Note
This function checks the difference between the current and previous flow rates to determine convergence.
Definition at line 324 of file CCircuit.cpp.
{
    for (const auto& unit : units) {
        if (std::abs(unit.current_F_g - unit.previous_F_g) > tol ||
            std::abs(unit.current_F_w- unit.previous_F_w) > tol) {
            return false;
        }
    }
    return true;
}
References units.
Referenced by iterate_units().
Check_Validity()
bool Circuit::Check_Validity (int vector_size, int * circuit_vector, bool if_debug = false)
Checks the validity of the circuit configuration.
Parameters
vector_size Size of the circuit vector.
circuit_vector Pointer to the circuit vector.
if_debug Boolean flag to print debug information.
Returns
true if the circuit is valid.
false if the circuit is invalid.
Note
The function performs several checks to ensure the circuit configuration is valid.
Definition at line 13 of file CCircuit.cpp.
{
    // initialize validation
    validation[0] = false;
    validation[1] = false;
    validation[2] = false;
    // check if there are no units, return false
    if (this->units.size() <= 0) {
        //cout why
        if (if_debug){
            std::cout << "No units in the circuit" << std::endl;
        }
        return false;
    }
    // check if vector_size is correct
    if (vector_size != 3 * this->units.size() + 1) {
        //print every element in the vector
        if (if_debug){
            std::cout << "Vector size is incorrect" << std::endl;
            for (int i = 0; i < vector_size; i++) {
                std::cout << circuit_vector[i] << " ";
            }
            std::cout << units.size() << std::endl;
            std::cout << vector_size << std::endl;
        }
        return false;
    }
    // get feed_num
    int feed_num = circuit_vector[0];
    // check if feed_num is valid: 0 <= feed_num < num_units
    if (feed_num < 0 || feed_num >= this->units.size()) {
        if (if_debug){
            std::cout << "Feed number is invalid" << std::endl;
        }
        return false;
    }
    // initialize connections for each unit
    for (int i = 0; i < this->units.size(); i++) {
        this->units[i].conc_num = circuit_vector[3 * i + 1];
        this->units[i].inter_num = circuit_vector[3 * i + 2];
        this->units[i].tails_num = circuit_vector[3 * i + 3];
        this->units[i].mark = false;
    }
    // mark units starting from feed_num
    mark_units(feed_num);
    // check if all units are marked
    for (int i = 0; i < units.size(); i++) {
        // if any unit is not marked, return false
        if (!this->units[i].mark) {
            if (if_debug){
                std::cout << "Not all units are connected" << std::endl;
            }
            return false;
        }
        // if any unit has self loop, return false
        if (this->units[i].conc_num == i || this->units[i].inter_num == i || this->units[i].tails_num == i) {
            if (if_debug){
                std::cout << "Unit " << i << " has self loop" << std::endl;
            }
            return false;
        }
        // if any unit has the same destination for all streams, return false
        if (this->units[i].conc_num == this->units[i].inter_num &&
            this->units[i].conc_num == this->units[i].tails_num &&
            this->units[i].inter_num == this->units[i].tails_num) {
            if (if_debug){
                std::cout << "Unit " << i << " has the same destination for all streams" << std::endl;
            }
            return false;
        }
        // ensure that the concentrate stream (conc_num) and tailings stream (tails_num) do not point to invalid units
        if (this->units[i].conc_num == this->units.size() + 1 || this->units[i].tails_num == this->units.size()) {
            if (if_debug){
                std::cout << "Unit " << i << " has invalid concentrate or tailings stream" << std::endl;
            }
            return false;
        }
        // bounds check
        if (this->units[i].conc_num < 0 || this->units[i].conc_num > this->units.size() + 1) {
            if (if_debug){
                std::cout << "Unit " << i << " has invalid concentrate stream range" << std::endl;
            }
            return false;
        }
        if (this->units[i].inter_num < 0 || this->units[i].inter_num > this->units.size() + 1) {
            if (if_debug){
                std::cout << "Unit " << i << " has invalid intermediate stream range" << std::endl;
            }
            return false;
        }
        if (this->units[i].tails_num < 0 || this->units[i].tails_num > this->units.size() + 1) {
            if (if_debug){
                std::cout << "Unit " << i << " has invalid tails stream range" << std::endl;
            }
            return false;
        }
        // check the validation results
        // if there is only one unit, ensure effective concentrated and tailing stream
        // if there are multiple units, should also ensure no intermediate flow directly to the product
        if (this->units.size() == 1) {
            if (!validation[0] || !validation[2])
            {
                if (if_debug){
                    std::cout << "Unit " << i << " has no ensure effective concentrated and tailing stream" << std::endl;
                }
                return false;
            }
        } else {
            if (!validation[0] || validation[1] || !validation[2])
            {
                if (if_debug){
                    std::cout << "Unit " << i << " has no ensure effective concentrated and tailing stream" << std::endl;
                }
                return false;
            }
        }
    }
    return true;
}
References mark_units(), units, and validation.
Referenced by gridSearch::hyperParameterSearch(), and main().
evaluate_performance()
double Circuit::evaluate_performance ()
Evaluates the performance of the circuit.
Returns
double The performance value of the circuit.
Note
This function calculates the performance of the circuit based on the flow rates of valuable and waste materials.
Definition at line 334 of file CCircuit.cpp.
{
    double total_valuable = final_output[0].current_F_g;
    double total_waste = final_output[0].current_F_w;
//    double grade = total_valuable / (total_valuable + total_waste);
    return 100 * total_valuable - 750 * total_waste;
}
References final_output.
Referenced by Evaluate_Circuit().
get_all_input_units()
void Circuit::get_all_input_units ()
Retrieves all input units for all units in the circuit.
Note
This function populates the input_info of all units in the circuit.
Definition at line 168 of file CCircuit.cpp.
{
    for (int i = 0; i < units.size(); ++i) {
        get_input_units(units, i);
    }
}
References get_input_units(), and units.
Referenced by iterate_units().
get_final_output_source()
void Circuit::get_final_output_source (std::array< CUnit, 2 > & outputs, std::vector< CUnit > & Units)
Retrieves all input units for the final output in the circuit.
Parameters
outputs Array of final output units.
Units Vector of circuit units.
Note
This function populates the input_info of the final output units with the units that contribute to their input streams.
Definition at line 175 of file CCircuit.cpp.
{
    for (int j = 0; j < 2; ++j) {
        for (int i = 0; i < Units.size(); ++i) {
            if (Units[i].conc_num == Units.size() + j) {
                final_output[j].input_info.emplace_back(i, 0); // 0 represents concentrate stream
            }
            if (Units[i].inter_num == Units.size() + j) {
                final_output[j].input_info.emplace_back(i, 1); // 1 represents intermediate stream
            }
            if (Units[i].tails_num == Units.size() + j) {
                final_output[j].input_info.emplace_back(i, 2); // 2 represents tails stream
            }
        }
    }
}
References final_output.
Referenced by iterate_units().
get_input_units()
void Circuit::get_input_units (std::vector< CUnit > & Units, int unit_num)
Retrieves all input units for a single unit in the circuit.
Parameters
Units Vector of units in the circuit.
unit_num The unit number for which input units are retrieved.
Note
This function populates the input_info of the specified unit with its input units.
Definition at line 153 of file CCircuit.cpp.
{
    for (int i = 0; i < Units.size(); ++i) {
        if (Units[i].conc_num == unit_num) {
            Units[unit_num].input_info.emplace_back(i, 0);  // 0  concentrated
        }
        if (Units[i].inter_num == unit_num) {
            Units[unit_num].input_info.emplace_back(i, 1);  // 1  intermediate
        }
        if (Units[i].tails_num == unit_num) {
            Units[unit_num].input_info.emplace_back(i, 2);  // 2  tails
        }
    }
}
Referenced by get_all_input_units().
initialize_units()
void Circuit::initialize_units (int * circuit_vector, double F_in_valuable, double F_in_waste)
Initializes the units in the circuit.
Parameters
circuit_vector Pointer to the circuit vector.
F_in_valuable Initial valuable flow rate.
F_in_waste Initial waste flow rate.
Note
This function sets up the initial configuration of the circuit units.
Definition at line 138 of file CCircuit.cpp.
{
    initial_F_g = F_in_valuable;
    initial_F_w = F_in_waste;
    auto vec = circuit_vector;
    first_feed = vec[0];
    for (int i = 0; i < units.size(); ++i) {
        units[i].self_num = i;
        units[i].conc_num = vec[i * 3 + 1];
        units[i].inter_num = vec[i * 3 + 2];
        units[i].tails_num = vec[i * 3 + 3];
        units[i].mark = false;
    }
}
References first_feed, initial_F_g, initial_F_w, and units.
Referenced by Evaluate_Circuit().
iterate_units()
void Circuit::iterate_units (int max_iterations, double tol)
Iterates through the units in the circuit until convergence or maximum iterations are reached.
Parameters
max_iterations Maximum number of iterations.
tol Convergence tolerance.
Note
This function simulates the circuit until the results converge or the maximum number of iterations is reached.
Definition at line 250 of file CCircuit.cpp.
{
    get_all_input_units();
    get_final_output_source(final_output, units);
    int iterations = 0;
    for (int i = 0; i < max_iterations; i++) {
        //std::cout << "Iteration: " << iterations << std::endl;
        for (auto& unit : units) {
            unit.save_current_input_flow();
            unit.reset_input_flow();
        }
        for (auto& output : final_output) {
            output.save_current_input_flow();
            output.reset_input_flow();
        }
        if (iterations == 0) {
            // use initial guess as the feed for every unit
            for (int i = 0; i < units.size(); i++) {
                units[i].initialise_flow(initial_F_g, initial_F_w);
            }
        }
        units[first_feed].initialise_flow(initial_F_g, initial_F_w);
        update_input(units);
        //print unit 0's input
        for (auto& unit : units) {
            if (unit.current_F_g + unit.current_F_w == 0) {
                continue;
            }
            one_unit(unit);
        }
        update_final_output(this->final_output, units);
        // visualise the units
        // for (auto& unit : units) {
        //     unit.visualize();
        // }
        converged = check_convergence(tol);
        if (converged) {
            break;
        }
        iterations++;
    }
}
References check_convergence(), converged, final_output, first_feed, get_all_input_units(), get_final_output_source(), initial_F_g, initial_F_w, one_unit(), output, units, update_final_output(), and update_input().
Referenced by Evaluate_Circuit().
mark_units()
void Circuit::mark_units (int unit_num) private
Marks the units starting from a given unit number.
Parameters
unit_num The starting unit number for marking.
Note
This function recursively marks units connected to the given unit.
Definition at line 298 of file CCircuit.cpp.
{
    if (this->units[unit_num].mark) return;
    this->units[unit_num].mark = true;
    // if conc_num points to another unit, recursively call mark_units
    if (this->units[unit_num].conc_num < this->units.size()) {
        mark_units(this->units[unit_num].conc_num);
    } else {
        validation[0] = true;
    }
    // if inter_num points to another unit, recursively call mark_units
    if (this->units[unit_num].inter_num < this->units.size()) {
        mark_units(this->units[unit_num].inter_num);
    } else {
        validation[1] = true;
    }
    // if tails_num points to another unit, recursively call mark_units
    if (this->units[unit_num].tails_num < this->units.size()) {
        mark_units(this->units[unit_num].tails_num);
    } else {
        validation[2] = true;
    }
}
References mark_units(), units, and validation.
Referenced by Check_Validity(), and mark_units().
one_unit()
void Circuit::one_unit (CUnit & cunit)
Calculates the flow rates for a single unit.
Parameters
cunit Reference to the unit for which flow rates are calculated.
Note
This function calculates the flow rates for concentrate, intermediate, and tails streams.
Definition at line 232 of file CCircuit.cpp.
{
    // calculate tau
    cunit.calculate_tau(cunit.current_F_g, cunit.current_F_w);
    // calculate recovery rates
    cunit.calculate_recovery_rates();
    // calculate flow out rates
    cunit.C_g = cunit.current_F_g* cunit.R_C_G;
    cunit.C_w = cunit.current_F_w* cunit.R_C_W;
    cunit.I_g = cunit.current_F_g* cunit.R_I_G;
    cunit.I_w = cunit.current_F_w* cunit.R_I_W;
    cunit.T_g = cunit.current_F_g* (1 - cunit.R_C_G - cunit.R_I_G);
    cunit.T_w = cunit.current_F_w* (1 - cunit.R_C_W - cunit.R_I_W);
}
References CUnit::C_g, CUnit::C_w, CUnit::calculate_recovery_rates(), CUnit::calculate_tau(), CUnit::current_F_g, CUnit::current_F_w, CUnit::I_g, CUnit::I_w, CUnit::R_C_G, CUnit::R_C_W, CUnit::R_I_G, CUnit::R_I_W, CUnit::T_g, and CUnit::T_w.
Referenced by iterate_units().
update_final_output()
void Circuit::update_final_output (std::array< CUnit, 2 > & fin_output, std::vector< CUnit > & cunits)
Updates the final output with the geradium and waste received.
Parameters
fin_output Array of final output units.
cunits Vector of circuit units.
Note
This function updates the final output units with the flow rates from the input units.
Definition at line 191 of file CCircuit.cpp.
{
    for (int j = 0; j < 2; ++j) {
        for (int i = 0; i < fin_output[j].input_info.size(); ++i) {
            int input_unit_num = fin_output[j].input_info[i].first;
            int input_type = fin_output[j].input_info[i].second;
            if (input_type == 0) {
                fin_output[j].current_F_g += cunits[input_unit_num].C_g;
                fin_output[j].current_F_w += cunits[input_unit_num].C_w;
            } else if (input_type == 1) {
                fin_output[j].current_F_g += cunits[input_unit_num].I_g;
                fin_output[j].current_F_w += cunits[input_unit_num].I_w;
            } else if (input_type == 2) {
                fin_output[j].current_F_g += cunits[input_unit_num].T_g;
                fin_output[j].current_F_w += cunits[input_unit_num].T_w;
            }
        }
    }
}
Referenced by iterate_units().
update_input()
void Circuit::update_input (std::vector< CUnit > & units)
Updates the input flow rates for all units in the circuit.
Parameters
units Vector of units in the circuit.
Note
This function updates the current input flow rates for each unit based on its input units.
Definition at line 211 of file CCircuit.cpp.
{
    for (int j = 0; j < units.size(); ++j) {
        int num_of_inputs = units[j].input_info.size();
        for (int i = 0; i < num_of_inputs; ++i) {
            int input_unit_num = units[j].input_info[i].first;
            int input_type = units[j].input_info[i].second;
            if (input_type == 0) {
                units[j].current_F_g += units[input_unit_num].C_g;
                units[j].current_F_w += units[input_unit_num].C_w;
            } else if (input_type == 1) {
                units[j].current_F_g += units[input_unit_num].I_g;
                units[j].current_F_w += units[input_unit_num].I_w;
            } else if (input_type == 2) {
                units[j].current_F_g += units[input_unit_num].T_g;
                units[j].current_F_w += units[input_unit_num].T_w;
            }
        }
    }
}
References units.
Referenced by iterate_units().
Member Data Documentation
converged
bool Circuit::converged
Definition at line 18 of file CCircuit.h.
Referenced by iterate_units().
final_output
std::array<CUnit,2> Circuit::final_output
Definition at line 138 of file CCircuit.h.
Referenced by evaluate_performance(), get_final_output_source(), and iterate_units().
first_feed
int Circuit::first_feed
Definition at line 17 of file CCircuit.h.
Referenced by initialize_units(), and iterate_units().
initial_F_g
double Circuit::initial_F_g
Definition at line 15 of file CCircuit.h.
Referenced by initialize_units(), and iterate_units().
initial_F_w
double Circuit::initial_F_w
Definition at line 16 of file CCircuit.h.
Referenced by initialize_units(), and iterate_units().
output
std::vector<double> Circuit::output
Definition at line 137 of file CCircuit.h.
Referenced by iterate_units().
units
std::vector<CUnit> Circuit::units
Definition at line 136 of file CCircuit.h.
Referenced by Circuit(), check_convergence(), Check_Validity(), get_all_input_units(), initialize_units(), iterate_units(), mark_units(), and update_input().
validation
bool Circuit::validation[3] private
Definition at line 150 of file CCircuit.h.
Referenced by Check_Validity(), and mark_units().
The documentation for this class was generated from the following files:
include/CCircuit.h
src/CCircuit.cpp