ACS-GERARDIUM-RUSH-SPHALERITE: GeneticAlgorithmUtils Class Reference
GeneticAlgorithmUtils Class Reference
#include <Genetic_Algorithm.h>
Static Public Member Functions
static void showProgress (double progress)
Displays a progress bar on the console.
static void completeProgressBar ()
Completes the progress bar by moving to a new line.
static int randomInt (int min, int max)
Generates a random integer between min and max (inclusive).
static bool shouldMutate (double mutationRate)
Determines whether a mutation should occur based on the mutation rate.
static void evaluateFitness (int **population, int numPopulation, double *fitness, int vector_size, double(&func)(int, int *), std::function< bool(int, int *)> validity)
Evaluate the fitness of the population.
static void initializeFixPopulation (int **population, int numPopulation, int num_of_units, std::function< bool(int, int *)> validity)
Initialize the population with only valid individuals.
static void selectParents (const double *fitness, int numPopulation, int numParents, std::vector< int > &idx)
Select parents for the next generation based on their fitness.
static void selectParentsTournament (const double *fitness, int numPopulation, std::vector< int > &idx, int tournament_size)
Selects parents using tournament selection.
static void elitism (int **population, const double *fitness, int **newPopulation, int numPopulation, int numElites)
Applies elitism to retain the best individuals.
static void mutate_inversion (int *individual, int vector_size, double mutationRate)
Applies inversion mutation to an individual.
static void mutate_delete_and_insert (int vector_size, int *offspring, double mutationRate, int N)
Applies delete and insert mutation to an individual.
static void uniformCrossover (int vector_size, int *parent1, int *parent2, int *offspring)
Perform crossover to produce offspring from two parents.
static void crossover_one_point (int vector_size, int *parent1, int *parent2, int *offspring, int numCross, double crossoverProbability)
Perform crossover to produce offspring from two parents.
static void crossover_two_point (int vector_size, int *parent1, int *parent2, int *offspring, int numCross, double crossoverProbability)
Perform crossover to produce offspring from two parents.
static void crossover_multiple (int vector_size, int *parent1, int *parent2, int *offspring, int numCross, double crossoverProbability)
Perform crossover to produce offspring from two parents.
static void mutate_substitution (int vector_size, int *individual, double mutationRate, int N)
Mutate an individual by randomly substituting one of its elements.
Detailed Description
Definition at line 25 of file Genetic_Algorithm.h.
Member Function Documentation
completeProgressBar()
void GeneticAlgorithmUtils::completeProgressBar () static
Completes the progress bar by moving to a new line.
This method is typically called after the progress has reached 100%.
Definition at line 32 of file Genetic_Algorithm.cpp.
{
    std::cout << std::endl;
}
Referenced by optimize().
crossover_multiple()
void GeneticAlgorithmUtils::crossover_multiple (int vector_size, int * parent1, int * parent2, int * offspring, int numCross, double crossoverProbability) static
Perform crossover to produce offspring from two parents.
Parameters
vector_size Size of each individual vector.
parent1 Pointer to the first parent.
parent2 Pointer to the second parent.
offspring Pointer to the offspring.
numCross Number of crossover points.
crossoverProbability Probability of crossover occurring.
Definition at line 140 of file Genetic_Algorithm.cpp.
{
    static random_device rd;
    static mt19937 gen(rd());
    uniform_real_distribution<> dis(0, 1);
    if (dis(gen) < crossoverProbability) {
        vector<int> crossoverPoints(numCross);  // Custom number of crossover points
        for (int& point : crossoverPoints) {
            point = GeneticAlgorithmUtils::randomInt(1, vector_size - 1);
        }
        sort(crossoverPoints.begin(), crossoverPoints.end());
        bool fromParent1 = true;
        int lastCrossoverPoint = 0;
        for (int point : crossoverPoints) {
            for (int j = lastCrossoverPoint; j < point; ++j) {
                offspring[j] = fromParent1 ? parent1[j] : parent2[j];
            }
            fromParent1 = !fromParent1;
            lastCrossoverPoint = point;
        }
        for (int j = lastCrossoverPoint; j < vector_size; ++j) {
            offspring[j] = fromParent1 ? parent1[j] : parent2[j];
        }
    } else {
        copy(parent1, parent1 + vector_size, offspring);
    }
}
References randomInt().
Referenced by optimize().
crossover_one_point()
void GeneticAlgorithmUtils::crossover_one_point (int vector_size, int * parent1, int * parent2, int * offspring, int numCross, double crossoverProbability) static
Perform crossover to produce offspring from two parents.
Parameters
vector_size Size of each individual vector.
parent1 Pointer to the first parent.
parent2 Pointer to the second parent.
offspring Pointer to the offspring.
numCross Number of crossover points.
crossoverProbability Probability of crossover occurring.
Definition at line 121 of file Genetic_Algorithm.cpp.
{
    static std::random_device rd;
    static std::mt19937 gen(rd());
    std::uniform_real_distribution<> dis(0, 1);
    if (dis(gen) < crossoverProbability) {
        int crossoverPoint = GeneticAlgorithmUtils::randomInt(1, vector_size - 1);
        for (int i = 0; i < crossoverPoint; ++i) {
            offspring[i] = parent1[i];
        }
        for (int i = crossoverPoint; i < vector_size; ++i) {
            offspring[i] = parent2[i];
        }
    } else {
        std::copy(parent1, parent1 + vector_size, offspring);
    }
}
References randomInt().
crossover_two_point()
void GeneticAlgorithmUtils::crossover_two_point (int vector_size, int * parent1, int * parent2, int * offspring, int numCross, double crossoverProbability) static
Perform crossover to produce offspring from two parents.
Parameters
vector_size Size of each individual vector.
parent1 Pointer to the first parent.
parent2 Pointer to the second parent.
offspring Pointer to the offspring.
numCross Number of crossover points.
crossoverProbability Probability of crossover occurring.
Definition at line 93 of file Genetic_Algorithm.cpp.
{
    static std::random_device rd;
    static std::mt19937 gen(rd());
    std::uniform_real_distribution<> dis(0, 1);
    if (dis(gen) < crossoverProbability) {
        int crossoverPoint1 = GeneticAlgorithmUtils::randomInt(1, vector_size - 1);
        int crossoverPoint2 = GeneticAlgorithmUtils::randomInt(1, vector_size - 1);
        // Ensure crossoverPoint1 is less than crossoverPoint2
        if (crossoverPoint1 > crossoverPoint2) {
            std::swap(crossoverPoint1, crossoverPoint2);
        }
        for (int i = 0; i < crossoverPoint1; ++i) {
            offspring[i] = parent1[i];
        }
        for (int i = crossoverPoint1; i < crossoverPoint2; ++i) {
            offspring[i] = parent2[i];
        }
        for (int i = crossoverPoint2; i < vector_size; ++i) {
            offspring[i] = parent1[i];
        }
    } else {
        std::copy(parent1, parent1 + vector_size, offspring);
    }
}
References randomInt().
elitism()
void GeneticAlgorithmUtils::elitism (int ** population, const double * fitness, int ** newPopulation, int numPopulation, int numElites) static
Applies elitism to retain the best individuals.
Parameters
population Current population.
fitness Fitness values of the population.
newPopulation New population after elitism.
numPopulation Number of individuals in the population.
numElites Number of elites to retain.
Definition at line 192 of file Genetic_Algorithm.cpp.
{
    std::vector<int> eliteIndices(numPopulation);
    std::iota(eliteIndices.begin(), eliteIndices.end(), 0);
    std::partial_sort(eliteIndices.begin(), eliteIndices.begin() + numElites, eliteIndices.end(), [&](int a, int b) {
        return fitness[a] > fitness[b];
    });
    for (int i = 0; i < numElites; ++i) {
        std::copy(population[eliteIndices[i]], population[eliteIndices[i]] + numPopulation, newPopulation[i]);
    }
}
evaluateFitness()
void GeneticAlgorithmUtils::evaluateFitness (int ** population, int numPopulation, double * fitness, int vector_size, double(&)(int, int *) func, std::function< bool(int, int *)> validity) static
Evaluate the fitness of the population.
Parameters
population Pointer to the population array.
numPopulation Number of individuals in the population.
fitness Pointer to the fitness array.
vector_size Size of each individual vector.
func Function to evaluate the fitness.
validity Function to check the validity of an individual.
Definition at line 54 of file Genetic_Algorithm.cpp.
{
//    #pragma omp parallel for
    for (int i = 0; i < numPopulation; ++i) {
        if (validity(vector_size, population[i])) {
            fitness[i] = func(vector_size, population[i]);
        } else {
            fitness[i] = -std::numeric_limits<double>::infinity();  // Set fitness to negative infinity for invalid solutions
        }
    }
}
Referenced by optimize().
initializeFixPopulation()
void GeneticAlgorithmUtils::initializeFixPopulation (int ** population, int numPopulation, int num_of_units, std::function< bool(int, int *)> validity) static
Initialize the population with only valid individuals.
Parameters
population Pointer to the population array.
numPopulation Number of individuals in the population.
num_of_units Number of units in the circuit.
validity Function to check the validity of an individual.
Definition at line 65 of file Genetic_Algorithm.cpp.
{
    int vector_size = num_of_units * 3 + 1;
//    #pragma omp parallel for
    for (int i = 0; i < numPopulation; ++i) {
        do {
            population[i][0] = GeneticAlgorithmUtils::randomInt(0, num_of_units);
            for (int j = 1; j < vector_size; ++j) {
                population[i][j] = GeneticAlgorithmUtils::randomInt(0, num_of_units + 1);
            }
        } while (!validity(vector_size, population[i]));
    }
}
References randomInt().
Referenced by optimize().
mutate_delete_and_insert()
void GeneticAlgorithmUtils::mutate_delete_and_insert (int vector_size, int * offspring, double mutationRate, int N) static
Applies delete and insert mutation to an individual.
Parameters
vector_size Size of the circuit vector.
offspring Offspring to be mutated.
mutationRate Mutation rate.
N Range of random values.
Definition at line 217 of file Genetic_Algorithm.cpp.
{
    if (GeneticAlgorithmUtils::shouldMutate(mutationRate)) {
        int deletePos = GeneticAlgorithmUtils::randomInt(0, vector_size - 1);
        std::copy(offspring + deletePos + 1, offspring + vector_size, offspring + deletePos);
        int insertPos = GeneticAlgorithmUtils::randomInt(0, vector_size - 2);
        int newValue = GeneticAlgorithmUtils::randomInt(0, N);
        std::copy_backward(offspring + insertPos, offspring + vector_size - 1, offspring + vector_size);
        offspring[insertPos] = newValue;
    }
}
References randomInt(), and shouldMutate().
mutate_inversion()
void GeneticAlgorithmUtils::mutate_inversion (int * individual, int vector_size, double mutationRate) static
Applies inversion mutation to an individual.
Parameters
individual Individual to be mutated.
vector_size Size of the circuit vector.
mutationRate Mutation rate.
Definition at line 204 of file Genetic_Algorithm.cpp.
{
    static std::random_device rd;
    static std::mt19937 gen(rd());
    std::uniform_real_distribution<> dis(0.0, 1.0);
    if (dis(gen) < mutationRate) {
        int start = GeneticAlgorithmUtils::randomInt(0, vector_size - 2);
        int end = GeneticAlgorithmUtils::randomInt(start + 1, vector_size - 1);
        std::reverse(individual + start, individual + end + 1);
    }
}
References randomInt().
mutate_substitution()
void GeneticAlgorithmUtils::mutate_substitution (int vector_size, int * individual, double mutationRate, int N) static
Mutate an individual by randomly substituting one of its elements.
Parameters
vector_size Size of the individual vector.
individual Pointer to the individual.
mutationRate Probability of mutation occurring.
N Range for random substitution.
Definition at line 169 of file Genetic_Algorithm.cpp.
{
    if (GeneticAlgorithmUtils::shouldMutate(mutationRate)) {
        int pos = GeneticAlgorithmUtils::randomInt(0, vector_size - 1);
        individual[pos] = GeneticAlgorithmUtils::randomInt(0, N);
    }
}
References randomInt(), and shouldMutate().
Referenced by optimize().
randomInt()
int GeneticAlgorithmUtils::randomInt (int min, int max) static
Generates a random integer between min and max (inclusive).
This method uses a Mersenne Twister pseudo-random generator seeded with a fixed value.
Parameters
min The minimum value of the random integer.
max The maximum value of the random integer.
Returns
A random integer between min and max.
Definition at line 36 of file Genetic_Algorithm.cpp.
{
    static std::random_device rd;
    static std::mt19937 gen(1234);
    std::uniform_int_distribution<> dis(min, max);
    return dis(gen);
}
Referenced by crossover_multiple(), crossover_one_point(), crossover_two_point(), initializeFixPopulation(), mutate_delete_and_insert(), mutate_inversion(), mutate_substitution(), optimize(), and selectParentsTournament().
selectParents()
void GeneticAlgorithmUtils::selectParents (const double * fitness, int numPopulation, int numParents, std::vector< int > & idx) static
Select parents for the next generation based on their fitness.
Parameters
fitness Pointer to the fitness array.
numPopulation Number of individuals in the population.
numParents Number of parents to select.
idx Vector to store the indices of the selected parents.
Definition at line 78 of file Genetic_Algorithm.cpp.
{
    iota(idx.begin(), idx.end(), 0);
    sort(idx.begin(), idx.end(), [&](int a, int b) { return fitness[a] > fitness[b]; });
    idx.resize(numParents);  // Select the top numParents individuals
}
Referenced by optimize().
selectParentsTournament()
void GeneticAlgorithmUtils::selectParentsTournament (const double * fitness, int numPopulation, std::vector< int > & idx, int tournament_size) static
Selects parents using tournament selection.
Parameters
fitness Fitness values of the population.
numPopulation Number of individuals in the population.
idx Indices of selected parents.
tournament_size Size of the tournament.
Definition at line 177 of file Genetic_Algorithm.cpp.
{
    std::vector<int> population_indices(numPopulation);
    std::iota(population_indices.begin(), population_indices.end(), 0);
    for (int i = 0; i < idx.size(); ++i) {
        std::vector<int> tournament(tournament_size);
        for (int j = 0; j < tournament_size; ++j) {
            tournament[j] = population_indices[GeneticAlgorithmUtils::randomInt(0, numPopulation - 1)];
        }
        idx[i] = *std::max_element(tournament.begin(), tournament.end(), [&](int a, int b) {
            return fitness[a] < fitness[b];
        });
    }
}
References randomInt().
shouldMutate()
bool GeneticAlgorithmUtils::shouldMutate (double mutationRate) static
Determines whether a mutation should occur based on the mutation rate.
This method generates a random double between 0.0 and 1.0 and compares it to the mutation rate.
Parameters
mutationRate A double value representing the probability of mutation (between 0.0 and 1.0).
Returns
True if a mutation should occur, otherwise false.
Definition at line 43 of file Genetic_Algorithm.cpp.
{
    static std::random_device rd;
    static std::mt19937 gen(1234);
    std::uniform_real_distribution<> dis(0.0, 1.0);
    return dis(gen) < mutationRate;
}
Referenced by mutate_delete_and_insert(), and mutate_substitution().
showProgress()
void GeneticAlgorithmUtils::showProgress (double progress) static
Displays a progress bar on the console.
The progress bar visually represents the progress of an operation.
Parameters
progress A double value between 0.0 and 1.0 representing the completion percentage.
Definition at line 19 of file Genetic_Algorithm.cpp.
{
    int barWidth = 70;
    std::cout << "[";
    int pos = barWidth * progress;
    for (int i = 0; i < barWidth; ++i) {
        if (i < pos) std::cout << "=";
        else if (i == pos) std::cout << ">";
        else std::cout << " ";
    }
    std::cout << "] " << int(progress * 100.0) << " %\r";
    std::cout.flush();
}
Referenced by optimize().
uniformCrossover()
void GeneticAlgorithmUtils::uniformCrossover (int vector_size, int * parent1, int * parent2, int * offspring) static
Perform crossover to produce offspring from two parents.
Parameters
vector_size Size of each individual vector.
parent1 Pointer to the first parent.
parent2 Pointer to the second parent.
offspring Pointer to the offspring.
Definition at line 84 of file Genetic_Algorithm.cpp.
{
    static random_device rd;
    static mt19937 gen(rd());
    uniform_int_distribution<> dis(0, 1);  // Distribution to decide gene inheritance
    for (int i = 0; i < vector_size; ++i) {
        offspring[i] = (dis(gen) == 0) ? parent1[i] : parent2[i];
    }
}
The documentation for this class was generated from the following files:
include/Genetic_Algorithm.h
src/Genetic_Algorithm.cpp