ACS-GERARDIUM-RUSH-SPHALERITE: include/CSimulator.h File Reference
CSimulator.h File Reference
Classes
struct Circuit_Parameters
Functions
double Evaluate_Circuit (int vector_size, int *circuit_vector, struct Circuit_Parameters parameters)
double Evaluate_Circuit (int vector_size, int *circuit_vector)
Function Documentation
Evaluate_Circuit() [1/2]
double Evaluate_Circuit (int vector_size, int * circuit_vector)
Definition at line 10 of file CSimulator.cpp.
{
    // Initialize the circuit
    Circuit circuit(((vector_size-1)/3));
    // Given the initial guess
    double initial_feed_gerardium = 10.0; // initial guess for F_g
    double initial_feed_waste = 90.0; // initial guess for F_w
    circuit.initialize_units(circuit_vector, initial_feed_gerardium, initial_feed_waste);
    // Define the maximum number of iterations and the tolerance
    int max_iterations = default_circuit_parameters.max_iterations;
    double tolerance = default_circuit_parameters.tolerance;
    //  Iterate the units
    circuit.iterate_units(max_iterations, tolerance);
    // Evaluate the performance of the circuit
    double performance = circuit.evaluate_performance();
    return performance;
}
References default_circuit_parameters, Circuit::evaluate_performance(), Circuit::initialize_units(), Circuit::iterate_units(), Circuit_Parameters::max_iterations, and Circuit_Parameters::tolerance.
Referenced by gridSearch::hyperParameterSearch(), and main().
Evaluate_Circuit() [2/2]
double Evaluate_Circuit (int vector_size, int * circuit_vector, struct Circuit_Parameters parameters)