ACS-GERARDIUM-RUSH-SPHALERITE: src/Genetic_Algorithm.cpp File Reference
Genetic_Algorithm.cpp File Reference
#include <iostream>
#include <cmath>
#include <array>
#include <vector>
#include <algorithm>
#include <random>
#include <cstdint>
#include <limits>
#include <numeric>
#include <functional>
#include "../include/Genetic_Algorithm.h"
#include "../include/CCircuit.h"
#include <omp.h>
Functions
bool all_true (int vector_size, int *vec)
Check if all elements in a vector are true.
int optimize (int vector_size, int *vec, double(&func)(int, int *), std::function< bool(int, int *)> validity, Algorithm_Parameters parameters)
Optimization function using a genetic algorithm.
Function Documentation
all_true()
bool all_true (int vector_size, int * vector)
Check if all elements in a vector are true.
Parameters
vector_size Size of the vector.
vec Pointer to the vector.
Returns
true Always returns true.
Definition at line 50 of file Genetic_Algorithm.cpp.
{
    return true;
}
optimize()
int optimize (int vector_size, int * vector, double(&)(int, int *) func, std::function< bool(int, int *)> validity = all_true, struct Algorithm_Parameters parameters = DEFAULT_ALGORITHM_PARAMETERS)
Optimization function using a genetic algorithm.
Parameters
vector_size Size of the individual vector.
vec Pointer to the vector.
func Function to evaluate the fitness.
validity Function to check the validity of an individual.
parameters Parameters for the genetic algorithm.
Returns
int Returns 0 on success.
Definition at line 230 of file Genetic_Algorithm.cpp.
{
    int numPopulation = parameters.numPopulation;  // Total population size
    int numParents = parameters.numParents;  // Number of parents
    int numOffspring = parameters.numOffspring;  // Number of offspring per generation
    int numGen = parameters.numGenerations;  // Number of generations
    int numCross = parameters.num_cross;  // Number of crossover points
    double crossoverProbability = parameters.crossoverProbability;  // Crossover probability
    double mutationRate = parameters.mutationRate;  // Mutation rate
    int num_of_units = (vector_size - 1) / 3;
    std::cout<<"Parameters initialised"<<std::endl;
    // Allocate memory for the population
    int** population = new int*[numPopulation];
    for (int i = 0; i < numPopulation; ++i) {
        population[i] = new int[vector_size];
    }
    // Allocate memory for the fitness array
    auto* fitness = new double[numPopulation];
    // Initialize the population with valid individuals
    std::cout<<"Initialising population"<<std::endl;
    GeneticAlgorithmUtils::initializeFixPopulation(population, numPopulation, num_of_units, validity);
    // Evaluate the initial population's fitness
    GeneticAlgorithmUtils::evaluateFitness(population, numPopulation, fitness, vector_size, func, validity);
    std::cout<<"Running the genetic algorithm"<<std::endl;
    // Main loop of the genetic algorithm
    for (int generation = 0; generation < numGen; ++generation) {
        vector<int> idx(numPopulation);
        GeneticAlgorithmUtils::selectParents(fitness, numPopulation, numParents, idx);
        // Generate offspring
//        #pragma omp parallel for
        for (int i = 0; i < numOffspring; ++i) {
            int parent1 = idx[GeneticAlgorithmUtils::randomInt(0, numParents - 1)];
            int parent2 = idx[GeneticAlgorithmUtils::randomInt(0, numParents - 1)];
            GeneticAlgorithmUtils::crossover_multiple(vector_size, population[parent1], population[parent2], population[numPopulation - numOffspring + i], numCross, crossoverProbability);
//            GeneticAlgorithmUtils::uniformCrossover(vector_size, population[parent1], population[parent2], population[numPopulation - numOffspring + i]);
            GeneticAlgorithmUtils::mutate_substitution(vector_size, population[numPopulation - numOffspring + i], mutationRate, num_of_units + 1);
        }
        // Evaluate the new population's fitness
        GeneticAlgorithmUtils::evaluateFitness(population, numPopulation, fitness, vector_size, func, validity);
        // Sort the entire population based on fitness
        vector<int> sortedIdx(numPopulation);
        iota(sortedIdx.begin(), sortedIdx.end(), 0);
        sort(sortedIdx.begin(), sortedIdx.end(), [&](int a, int b) { return fitness[a] > fitness[b]; });
        // Keep the top numPopulation individuals
        int** newPopulation = new int*[numPopulation];
        auto* newFitness = new double[numPopulation];
//        #pragma omp parallel for
        for (int i = 0; i < numPopulation; ++i) {
            newPopulation[i] = population[sortedIdx[i]];
            newFitness[i] = fitness[sortedIdx[i]];
        }
        // Replace old population with the new one
        delete[] population;
        delete[] fitness;
        population = newPopulation;
        fitness = newFitness;
        GeneticAlgorithmUtils::showProgress((double)(generation + 1) / numGen);
    }
    GeneticAlgorithmUtils::completeProgressBar();
    // Find the best solution in the final population
    int bestIdx = distance(fitness, max_element(fitness, fitness + numPopulation));
    copy(population[bestIdx], population[bestIdx] + vector_size, vec);
    // Free the memory of the final population
    for (int i = 0; i < numPopulation; ++i) {
        delete[] population[i];
    }
    delete[] population;
    // Free the memory of the fitness array
    delete[] fitness;
    return 0;  // Success
}
References GeneticAlgorithmUtils::completeProgressBar(), GeneticAlgorithmUtils::crossover_multiple(), Algorithm_Parameters::crossoverProbability, GeneticAlgorithmUtils::evaluateFitness(), GeneticAlgorithmUtils::initializeFixPopulation(), GeneticAlgorithmUtils::mutate_substitution(), Algorithm_Parameters::mutationRate, Algorithm_Parameters::num_cross, Algorithm_Parameters::numGenerations, Algorithm_Parameters::numOffspring, Algorithm_Parameters::numParents, Algorithm_Parameters::numPopulation, GeneticAlgorithmUtils::randomInt(), GeneticAlgorithmUtils::selectParents(), and GeneticAlgorithmUtils::showProgress().
Referenced by gridSearch::hyperParameterSearch(), and main().